version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  api:
    build: ./docker/api
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
  
  ui:
    build: ./docker/ui/Dockerfile
    volumes: 
      - ./ui:/app 
    depends_on: 
      - api 
    link: 
      - api 

  web:
    build: ./docker/nginx
    ports:
      - 8000:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend

  db:
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
