version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  api:
    build: ./docker/api
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
  
  ui:
    build: ./docker/ui
    volumes: 
      - ./frontend:/work/frontend
    environment: 
      PORT: '3000'
      HOST: '0.0.0.0'
      BASE_URL: 'http://nginx'
    ports: 
      - 3000:3000
    tty: true
    depends_on: 
      - api 
    links:  
      - api 

  web:
    build: ./docker/nginx
    ports:
      - 8000:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend

  db:
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
